version: "3"
services:
  usuarios-service:
    build: ./usuarios-service
    ports:
      - "5001:5001"

  web-service:
    build: ./web-service
    ports:
      - "5000:5000"
    depends_on:
      - usuarios-service
